import {JobType} from "@/app/dashboard/jobs/job-type";

export const jobData: JobType[] = [
    {
        id: "1",
        occupation: "（契）技術職補助（鉄道建設業務）",
        employmentType: "フルタイム",
        date: "2021-08-01",
        deadline: "2021-08-31",
        company: "株式会社テスト",
        location: "東京都",
        summary: "テスト求人",
        contractType: "正社員",
        contractTypeOther: "",
        salary: "300000",
        workingHours: "9:00-18:00",
        holidays: "土日祝",
        age: "20-30",
        jobNumber: "12345",
        publicRange: "全体",
        jobLabels: ["週休二日制（土日休）", "残業なし", "交通費支給", "社会保険完備"],
        jobCount: 1
    },
    {
        id: "2",
        occupation: "（契）一般事務（Ａ）（旭川市）",
        employmentType: "フルタイム",
        date: "2021-08-01",
        deadline: "2021-08-31",
        company: "株式会社テスト",
        location: "東京都",
        summary: "テスト求人",
        contractType: "正社員",
        contractTypeOther: "",
        salary: "300000",
        workingHours: "9:00-18:00",
        holidays: "土日祝",
        age: "20-30",
        jobNumber: "12345",
        publicRange: "全体",
        jobLabels: ["フルタイム"],
        jobCount: 1
    },
    {
        id: "3",
        occupation: "事務職（会計年度任用職員）",
        employmentType: "フルタイム",
        date: "2021-08-01",
        deadline: "2021-08-31",
        company: "株式会社テスト",
        location: "東京都",
        summary: "テスト求人",
        contractType: "正社員",
        contractTypeOther: "",
        salary: "300000",
        workingHours: "9:00-18:00",
        holidays: "土日祝",
        age: "20-30",
        jobNumber: "12345",
        publicRange: "全体",
        jobLabels: ["フルタイム"],
        jobCount: 1
    },
    {
        id: "4",
        occupation: "通訳・翻訳員（中国語）",
        employmentType: "フルタイム",
        date: "2021-08-01",
        deadline: "2021-08-31",
        company: "株式会社テスト",
        location: "東京都",
        summary: "テスト求人",
        contractType: "正社員",
        contractTypeOther: "",
        salary: "300000",
        workingHours: "9:00-18:00",
        holidays: "土日祝",
        age: "20-30",
        jobNumber: "12345",
        publicRange: "全体",
        jobLabels: ["フルタイム"],
        jobCount: 1
    },
    {
        id: "5",
        occupation: "案内スタッフ（北３西２）",
        employmentType: "フルタイム",
        date: "2021-08-01",
        deadline: "2021-08-31",
        company: "株式会社テスト",
        location: "東京都",
        summary: "テスト求人",
        contractType: "正社員",
        contractTypeOther: "",
        salary: "300000",
        workingHours: "9:00-18:00",
        holidays: "土日祝",
        age: "20-30",
        jobNumber: "12345",
        publicRange: "全体",
        jobLabels: ["フルタイム"],
        jobCount: 1
    },
];
